media:
  input: assets/images
  output: assets/images
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [cover, title]
    fields:
      - { name: layout, type: string, hidden: true, default: post }
      - { name: image, label: Cover image, type: image }
      - { name: title, label: Title, type: string, required: true }
      - {
          name: categories,
          label: Categories,
          type: select,
          options: { values: ["misc", "junk", "Blog", "Moving", "Sweden"] },
        }
      - { name: author, label: Authors, type: string }
      - { name: body, label: Body, type: rich-text }
  - name: music_records
    label: Music Records
    path: _data/music-records.yaml
    type: file
    fields:
      - name: title
        label: Record title
        type: string
      - name: artist
        label: Artist
        type: string
      - name: image
        label: cover image
        type: image
        description: The cover image
      - name: record-image
        label: record image
        type: image
        description: The record image
    
