title: Arnes Blog
author:
  name: Arne
  email: arne.rossmann@gmail.com
description: My blog conserving my thoughts and some aspects of my life.
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
